<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QT-INNO-LT0004" ignored="0" name="Weather_Verification_Test" tests="10" failures="4" timestamp="03 Jul 2021 12:36:16 GMT" time="38.198" errors="0">
  <testcase name="Test01_verify_Access_To_Weather_API_For_invalid_CityName_Input_And_Check_Response_Status_Code" time="2.361" classname="automation.tests.Weather_Verification_API_Test"/>
  <testcase name="Test02_verify_Access_To_Weather_API_And_Check_Response_Status_Code" time="0.178" classname="automation.tests.Weather_Verification_API_Test"/>
  <testcase name="Test03_verify_Weather_Condition_In_WeatherAPI_Response" time="1.05" classname="automation.tests.Weather_Verification_API_Test"/>
  <testcase name="Test04_verify_Weather_Temperature_In_WeatherAPI_Response" time="0.038" classname="automation.tests.Weather_Verification_API_Test">
    <failure type="java.lang.AssertionError" message="[ASSERT FAILED]: Condition value is different in API and UI responseAPI response: Clouds UI data: Clear expected [Clear] but found [Clouds]">
      <![CDATA[java.lang.AssertionError: [ASSERT FAILED]: Condition value is different in API and UI responseAPI response: Clouds UI data: Clear expected [Clear] but found [Clouds]
at automation.APIkeywords.WeatherAPI.compareWeatherConditionDataFromUIAndAPI(WeatherAPI.java:65)
at automation.tests.Weather_Verification_API_Test.Test04_verify_Weather_Temperature_In_WeatherAPI_Response(Weather_Verification_API_Test.java:40)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test04_verify_Weather_Temperature_In_WeatherAPI_Response -->
  <testcase name="Test01_Launch_Application_And_Verify_User_Navigation_To_HomePage" time="15.541" classname="automation.tests.Weather_Verification_Test"/>
  <testcase name="Test02_Click_On_Weather_Tab_And_Verify_User_Navigates_To_Weather_Page" time="1.874" classname="automation.tests.Weather_Verification_Test"/>
  <testcase name="Test03_enter_City_And_Verify_City_Is_Displayed_In_Map" time="11.365" classname="automation.tests.Weather_Verification_Test">
    <failure type="java.lang.AssertionError" message="[ASSERT FAILED]: Element cityCheckbox not found on the WeatherPage !!!">
      <![CDATA[java.lang.AssertionError: [ASSERT FAILED]: Element cityCheckbox not found on the WeatherPage !!!
at automation.base.GetPage.elemconstructed_dynamically(GetPage.java:58)
at automation.keywords.WeatherPage.selectCheckboxForCityIfNotSelected(WeatherPage.java:49)
at automation.keywords.WeatherPage.enterCityInPinYourCityTextFieldAndSelect(WeatherPage.java:45)
at automation.tests.Weather_Verification_Test.Test03_enter_City_And_Verify_City_Is_Displayed_In_Map(Weather_Verification_Test.java:38)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Test03_enter_City_And_Verify_City_Is_Displayed_In_Map -->
  <testcase name="Test04_Verify_City_Weather_Information_Displayed_In_Map" time="0.02" classname="automation.tests.Weather_Verification_Test">
    <failure type="java.lang.AssertionError" message="[ASSERT FAILED]: Element mapCity not found on the WeatherPage !!!">
      <![CDATA[java.lang.AssertionError: [ASSERT FAILED]: Element mapCity not found on the WeatherPage !!!
at automation.base.GetPage.elemconstructed_dynamically(GetPage.java:58)
at automation.keywords.WeatherPage.storeCityWeatherInformation(WeatherPage.java:61)
at automation.tests.Weather_Verification_Test.Test04_Verify_City_Weather_Information_Displayed_In_Map(Weather_Verification_Test.java:44)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Test04_Verify_City_Weather_Information_Displayed_In_Map -->
  <testcase name="Test01_Compare_Weather_Condition_Data_From_UI_And_API" time="0.003" classname="automation.tests.Weather_Verification_Compare_Data_Test">
    <failure type="java.lang.AssertionError" message="[ASSERT FAILED]: Condition value is different in API and UI responseAPI response: Clouds UI data: Clear expected [Clear] but found [Clouds]">
      <![CDATA[java.lang.AssertionError: [ASSERT FAILED]: Condition value is different in API and UI responseAPI response: Clouds UI data: Clear expected [Clear] but found [Clouds]
at automation.APIkeywords.WeatherAPI.compareWeatherConditionDataFromUIAndAPI(WeatherAPI.java:65)
at automation.tests.Weather_Verification_Compare_Data_Test.Test01_Compare_Weather_Condition_Data_From_UI_And_API(Weather_Verification_Compare_Data_Test.java:26)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Test01_Compare_Weather_Condition_Data_From_UI_And_API -->
  <testcase name="Test02_Compare_Weather_Temperature_Data_From_UI_And_API" time="0.008" classname="automation.tests.Weather_Verification_Compare_Data_Test"/>
</testsuite> <!-- Weather_Verification_Test -->
